apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: invert-image
  namespace: openfaas-fn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invert-image-test
  minReplicas: 1                                # Mínimo de réplicas
  maxReplicas: 8                                # Máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 3       
  behavior:
    scaleDown:                                 # Comportamiento escalado hacia abajo
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 20
      - type: Pods
        value: 3
        periodSeconds: 20
      selectPolicy: Min   
    scaleUp:
      stabilizationWindowSeconds: 0           # Comportamiento escalado hacia arriba
      policies:
      - type: Percent
        value: 100
        periodSeconds: 20
      - type: Pods
        value: 4
        periodSeconds: 20
      selectPolicy: Max
        