apiVersion: autoscaling/v2beta2     # Versión de la API de autoscaling
kind: HorizontalPodAutoscaler
metadata:
  name: prepare-image
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: prepare-image 
  minReplicas: 1                    # Mínimo de réplicas
  maxReplicas: 10                   # Máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: 80Mi
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 3       
  behavior:
    scaleDown:                                 # Comportamiento escalado hacia abajo
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 3
        periodSeconds: 30
      selectPolicy: Max   
    scaleUp:
      stabilizationWindowSeconds: 0           # Comportamiento escalado hacia arriba
      policies:
      - type: Pods
        value: 3
        periodSeconds: 30
      selectPolicy: Max


